import { cities, countries, professions } from "#lib";

export const educatorStepsConfig = {
  "Profile Setup": [
    {
      name: "avatar",
      label: "Profile Picture",
      type: "file",
      required: false,
    },
    {
      name: "firstName",
      label: "First Name",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ]+(?:[-' ][a-zA-ZÀ-ÿ]+)*$",
      minlength: 2,
      maxlength: 50,
      required: true,
    },
    {
      name: "lastName",
      label: "Last Name",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ]+(?:[-' ][a-zA-ZÀ-ÿ]+)*$",
      minlength: 2,
      maxlength: 50,
      required: true,
    },
    {
      name: "gender",
      label: "Gender",
      type: "select",
      options: ["Male", "Female", "Other"],
      required: true,
    },
    {
      name: "dateOfBirth",
      label: "Date of Birth",
      type: "date",
      required: true,
    },
    {
      name: "country",
      label: "Country",
      type: "select",
      options: countries,
      required: true,
    },
    {
      name: "city",
      label: "City",
      type: "select",
      options: cities,
      required: true,
    },
    {
      name: "fullAddress",
      label: "Full Address",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 50,
      maxlength: 200,
      required: true,
    },
    {
      name: "bio",
      label: "Bio",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 20,
      maxlength: 500,
      required: false,
    },
  ],
  Identity: [
    {
      name: "identityProof",
      label: "Identity Proof",
      type: "file",
      required: true,
    },
    {
      name: "criminalRecord",
      label: "Criminal Record",
      type: "file",
      required: true,
    },
  ],
  Profession: [
    {
      name: "profession",
      label: "Profession",
      type: "select",
      options: professions,
      required: true,
    },
    {
      name: "hourlyRate",
      label: "Hourly Rate",
      type: "number",
      step: 0.01,
      min: 0,
      max: 1000,
      required: true,
    },
    { name: "skills", label: "Skills", type: "text", required: true },
    {
      name: "education",
      label: "Education",
      type: "select",
      options: [
        "Bachelor's Degree",
        "Master's Degree",
        "PhD",
        "Professional Certification",
        "Other",
      ],
      required: true,
    },
    {
      name: "certificateOfHonor",
      label: "Certificate Of Honor",
      type: "file",
      required: false,
    },
    { name: "diploma", label: "Diploma", type: "file", required: false },
  ],
};

export const organizationStepsConfig = {
  "Profile Setup": [
    {
      name: "avatar",
      label: "Profile Picture",
      type: "file",
      required: false,
    },
    {
      name: "organizationName",
      label: "Organization Name",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 2,
      maxlength: 50,
      required: true,
    },
    {
      name: "foundedYear",
      label: "Founded Year",
      type: "date",
      required: false,
    },
    {
      name: "phone",
      label: "Contact Number",
      type: "tel",
      pattern: "^[0-9]{10,15}$",
      minlength: 10,
      maxlength: 15,
      required: true,
    },
    {
      name: "siretNumber",
      label: "SIRET Number",
      type: "text",
      pattern: "^[0-9]{14}$",
      minlength: 14,
      maxlength: 14,
      required: false,
    },
    {
      name: "country",
      label: "Country",
      type: "select",
      options: [
        "France",
        "Allemagne",
        "Norvège",
        "Suède",
        "Canada",
        "Pays-Bas",
        "Danemark",
        "Royaume-Uni",
        "Émirats Arabes Unis (UAE)",
      ],
      required: true,
    },
    {
      name: "city",
      label: "City",
      type: "select",
      options: [
        "Paris",
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice",
        "Berlin",
        "Munich",
        "Hambourg",
        "Francfort",
        "Cologne",
        "Oslo",
        "Bergen",
        "Trondheim",
        "Stavanger",
        "Drammen",
        "Stockholm",
        "Gothenburg",
        "Malmö",
        "Uppsala",
        "Västerås",
        "Toronto",
        "Vancouver",
        "Montréal",
        "Calgary",
        "Ottawa",
        "Amsterdam",
        "Rotterdam",
        "La Haye",
        "Utrecht",
        "Eindhoven",
        "Copenhague",
        "Aarhus",
        "Odense",
        "Aalborg",
        "Esbjerg",
        "Londres",
        "Manchester",
        "Birmingham",
        "Édimbourg",
        "Glasgow",
        "Dubaï",
        "Abou Dabi",
        "Charjah",
        "Ajman",
        "Fujairah",
      ],
      required: true,
    },
    {
      name: "officeAddress",
      label: "Office Address",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 50,
      maxlength: 200,
      required: true,
    },
    {
      name: "branches",
      label: "Add Branches",
      type: "branches",
      required: true,
    },
  ],
};
