import { citiesData, countriesData, professionsData } from "#lib";

export const educatorStepsConfig: Record<string, any[]> = {
  "Profile Setup": [
    {
      name: "avatar",
      label: "Photo de profil",
      type: "file",
      required: false,
    },
    {
      name: "firstName",
      label: "Prénom",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ]+(?:[-' ][a-zA-ZÀ-ÿ]+)*$",
      minlength: 2,
      maxlength: 50,
      required: true,
    },
    {
      name: "lastName",
      label: "Nom de famille",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ]+(?:[-' ][a-zA-ZÀ-ÿ]+)*$",
      minlength: 2,
      maxlength: 50,
      required: true,
    },
    {
      name: "gender",
      label: "Genre",
      type: "select",
      options: ["Homme", "Femme", "Autre"],
      required: true,
    },
    {
      name: "dateOfBirth",
      label: "Date de naissance",
      type: "date",
      required: true,
    },
    {
      name: "country",
      label: "Pays",
      type: "select",
      options: countriesData,
      required: true,
    },
    {
      name: "city",
      label: "Ville",
      type: "select",
      options: citiesData,
      required: true,
    },
    {
      name: "fullAddress",
      label: "Adresse complète",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 50,
      maxlength: 200,
      required: true,
    },
    {
      name: "bio",
      label: "Bio",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 20,
      maxlength: 500,
      required: false,
    },
  ],
  Identity: [
    {
      name: "identityProof",
      label: "Justificatif d'identité",
      type: "file",
      required: true,
    },
    {
      name: "criminalRecord",
      label: "Extrait de casier judiciaire",
      type: "file",
      required: true,
    },
  ],
  Profession: [
    {
      name: "profession",
      label: "Profession",
      type: "select",
      options: professionsData,
      required: true,
    },
    {
      name: "hourlyRate",
      label: "Taux horaire (€)",
      type: "number",
      step: 0.01,
      min: 0,
      max: 1000,
      required: true,
    },
    { name: "skills", label: "Compétences", type: "text", required: true },
    {
      name: "education",
      label: "Éducation",
      type: "select",
      options: [
        "Licence",
        "Master",
        "Doctorat",
        "Certification Professionnelle",
        "Autre",
      ],
      required: true,
    },
    {
      name: "certificateOfHonor",
      label: "Certificat d'honneurabilité",
      type: "file",
      required: false,
    },
    { name: "diploma", label: "Diplôme", type: "file", required: false },
  ],
};

export const organizationStepsConfig: Record<string, any[]> = {
  "Profile Setup": [
    {
      name: "avatar",
      label: "Photo de profil",
      type: "file",
      required: false,
    },
    {
      name: "organizationName",
      label: "Nom de l'organisation",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 2,
      maxlength: 50,
      required: true,
    },
    {
      name: "foundedYear",
      label: "Année de création",
      type: "date",
      required: false,
    },
    {
      name: "phone",
      label: "Numéro de contact",
      type: "tel",
      pattern: "^[0-9]{10,15}$",
      minlength: 10,
      maxlength: 15,
      required: true,
    },
    {
      name: "siretNumber",
      label: "Numéro SIRET",
      type: "text",
      pattern: "^[0-9]{14}$",
      minlength: 14,
      maxlength: 14,
      required: false,
    },
    {
      name: "country",
      label: "Pays",
      type: "select",
      options: [
        "France",
        "Germany",
        "Norway",
        "Sweden",
        "Canada",
        "Pays-Bas",
        "Danemark",
      ],
      required: true,
    },
    {
      name: "city",
      label: "Ville",
      type: "select",
      options: [
        "Région parisienne",
        "Amiens",
        "Arras",
        "Calais",
        "Dunkerque",
        "Lens",
        "Lille",
        "Caen",
        "Cherbourg-en-Cotentin",
        "Le Havre",
        "Rouen",
        "Évreux",
        "Brest",
        "Lorient",
        "Quimper",
        "Rennes",
        "Vannes",
        "Angers",
        "La Roche-sur-Yon",
        "Le Mans",
        "Nantes",
        "Saint-Nazaire",
        "Blois",
        "Bourges",
        "Chartres",
        "Orléans",
        "Tours",
        "Colmar",
        "Metz",
        "Mulhouse",
        "Nancy",
        "Reims",
        "Strasbourg",
        "Troyes",
        "Auxerre",
        "Belfort",
        "Besançon",
        "Chalon-sur-Saône",
        "Dijon",
        "Nevers",
        "Annecy",
        "Bourg-en-Bresse",
        "Chambéry",
        "Clermont-Ferrand",
        "Grenoble",
        "Lyon",
        "Saint-Étienne",
        "Valence",
        "Aix-en-Provence",
        "Arles",
        "Avignon",
        "Cannes",
        "Gap",
        "Marseille",
        "Nice",
        "Toulon",
        "Albi",
        "Béziers",
        "Montauban",
        "Montpellier",
        "Nîmes",
        "Perpignan",
        "Toulouse",
        "Angoulême",
        "Bayonne",
        "Bordeaux",
        "La Rochelle",
        "Limoges",
        "Niort",
        "Pau",
        "Poitiers",
        "Périgueux",
        "Cottbus",
        "Brandenburg an der Havel",
        "Frankfurt (Oder)",
        "Stuttgart",
        "Mannheim",
        "Karlsruhe",
        "Freiburg im Breisgau",
        "Heidelberg",
        "Ulm",
        "Heilbronn",
        "Pforzheim",
        "Reutlingen",
        "Tübingen",
        "Konstanz",
        "Ravensburg",
        "München (Munich)",
        "Nürnberg (Nuremberg)",
        "Augsburg",
        "Regensburg",
        "Ingolstadt",
        "Würzburg",
        "Erlangen",
        "Fürth",
        "Rosenheim",
        "Passau",
        "Landshut",
        "Bamberg",
        "Bayreuth",
        "Kempten (Allgäu)",
        "Köln (Cologne)",
        "Düsseldorf",
        "Dortmund",
        "Essen",
        "Duisburg",
        "Bochum",
        "Wuppertal",
        "Bonn",
        "Münster",
        "Bielefeld",
        "Aachen (Aix-la-Chapelle)",
        "Mönchengladbach",
        "Krefeld",
        "Hagen",
        "Siegen",
        "Paderborn",
        "Solingen",
        "Leverkusen",
        "Hannover (Hanovre)",
        "Braunschweig",
        "Wolfsburg",
        "Göttingen",
        "Osnabrück",
        "Oldenburg",
        "Hildesheim",
        "Lüneburg",
        "Wilhelmshaven",
        "Celle",
        "Frankfurt am Main",
        "Wiesbaden",
        "Darmstadt",
        "Kassel",
        "Gießen",
        "Marburg",
        "Fulda",
        "Offenbach am Main",
        "Hanau",
        "Mainz (Mayence)",
        "Ludwigshafen am Rhein",
        "Koblenz",
        "Kaiserslautern",
        "Trier (Trèves)",
        "Speyer",
        "Worms",
        "Neustadt an der Weinstraße",
        "Saarbrücken",
        "Neunkirchen",
        "Homburg",
        "Kiel",
        "Lübeck",
        "Flensburg",
        "Neumünster",
        "Rostock",
        "Schwerin",
        "Greifswald",
        "Stralsund",
        "Neubrandenburg",
        "Leipzig",
        "Dresden (Dresde)",
        "Chemnitz",
        "Zwickau",
        "Görlitz",
        "Plauen",
        "Magdeburg",
        "Halle (Saale)",
        "Dessau-Roßlau",
        "Wittenberg (Lutherstadt)",
        "Erfurt",
        "Jena",
        "Gera",
        "Weimar",
        "Eisenach",
        "Suhl",
        "Bremen (Brême)",
        "Bremerhaven",
        "Hamburg (Hambourg)",
        "R챕gion Oslo (Oslo + B챈rum + Asker + Lillestr첩m)",
        "Sandvika (B챈rum)",
        "Asker",
        "Lillestr첩m",
        "Jessheim (Ullensaker)",
        "Ski (Nordre Follo)",
        "Fredrikstad",
        "Sarpsborg",
        "Moss",
        "Halden",
        "Askim (Indre 횠stfold)",
        "Drammen",
        "Kongsberg",
        "H첩nefoss (Ringerike)",
        "Geilo (Hol)",
        "Hamar",
        "Lillehammer",
        "Gj첩vik",
        "Kongsvinger",
        "Elverum",
        "T첩nsberg",
        "Sandefjord",
        "Larvik",
        "Horten",
        "Skien",
        "Porsgrunn",
        "Notodden",
        "Krager첩",
        "Rjukan (Tinn)",
        "Kristiansand",
        "Arendal",
        "Grimstad",
        "Mandal (Lindesnes)",
        "Flekkefjord",
        "Stavanger",
        "Sandnes",
        "Haugesund",
        "Bryne (Time)",
        "Egersund",
        "Karm첩y (Kopervik/횇krehamn)",
        "Bergen",
        "Ask첩y",
        "Bj첩rnafjorden (Os)",
        "Stord (Leirvik)",
        "Odda (Ullensvang)",
        "Voss",
        "F첩rde (Sunnfjord)",
        "Sogndal",
        "Flor첩 (Kinn)",
        "횇lesund",
        "Molde",
        "Kristiansund",
        "Ulsteinvik (Ulstein)",
        "Sunndals첩ra (Sunndal)",
        "횠rsta",
        "Volda",
        "Trondheim",
        "Stj첩rdal",
        "Steinkjer",
        "Levanger",
        "Verdal",
        "Namsos",
        "Orkanger (Orkland)",
        "R첩ros",
        "Bod첩",
        "Mo i Rana",
        "Mosj첩en",
        "Narvik",
        "Sortland",
        "Svolv챈r (V책gan)",
        "Fauske",
        "Br첩nn첩ysund",
        "Troms첩",
        "Harstad",
        "Finnsnes (Senja)",
        "Bardufoss (M책lselv)",
        "Storslett (Nordreisa)",
        "Alta",
        "Hammerfest",
        "Kirkenes (S첩r-Varanger)",
        "Vads첩",
        "Vard첩",
        "Svalbard",
        "Södertälje",
        "Uppsala",
        "Norrtälje",
        "Västerås",
        "Eskilstuna",
        "Enköping",
        "Nyköping",
        "Katrineholm",
        "Strängnäs",
        "Linköping",
        "Norrköping",
        "Motala",
        "Köping",
        "Arboga",
        "Örebro",
        "Karlskoga",
        "Lindesberg",
        "Karlstad",
        "Arvika",
        "Kristinehamn",
        "Göteborg (Gothenburg)",
        "Borås",
        "Skövde",
        "Trollhättan",
        "Uddevalla",
        "Alingsås",
        "Lidköping",
        "Falköping",
        "Mariestad",
        "Halmstad",
        "Varberg",
        "Kungsbacka",
        "Falkenberg",
        "Malmö",
        "Lund",
        "Helsingborg",
        "Kristianstad",
        "Ystad",
        "Trelleborg",
        "Ängelholm",
        "Simrishamn",
        "Karlskrona",
        "Karlshamn",
        "Ronneby",
        "Växjö",
        "Älmhult",
        "Ljungby",
        "Kalmar",
        "Västervik",
        "Oskarshamn",
        "Borgholm (Öland)",
        "Jönköping",
        "Nässjö",
        "Värnamo",
        "Visby",
        "Gävle",
        "Sandviken",
        "Hudiksvall",
        "Falun",
        "Borlänge",
        "Mora",
        "Sundsvall",
        "Härnösand",
        "Örnsköldsvik",
        "Umeå",
        "Skellefteå",
        "Lycksele",
        "Luleå",
        "Kiruna",
        "Boden",
        "Piteå",
        "Gällivare",
        "Haparanda-Tornio",
        "Québec (Ville de Québec + Lévis)",
        "Gatineau (Agglomération Ottawa–Gatineau	 côté QC)",
        "Sherbrooke",
        "Trois-Rivières",
        "Saguenay (Chicoutimi–Jonquière)",
        "Drummondville",
        "Granby",
        "Saint-Jean-sur-Richelieu",
        "Rimouski",
        "Rivière-du-Loup",
        "Shawinigan",
        "Joliette",
        "Sorel‑Tracy",
        "Saint‑Jérôme",
        "Terrebonne–Mascouche (MRC Les Moulins)",
        "Repentigny–L’Assomption",
        "Val‑d’Or",
        "Rouyn‑Noranda",
        "Sept‑Îles",
        "Baie‑Comeau",
        "Gaspé",
        "Matane",
        "Victoriaville",
        "Thetford Mines",
        "Région du Grand Toronto (Toronto + Mississauga + Brampton + York + Durham + Halton)",
        "Région Hamilton–Niagara (Hamilton + St. Catharines–Niagara)",
        "Ottawa (côté ON)",
        "Kitchener–Waterloo–Cambridge",
        "London",
        "Windsor",
        "Kingston",
        "Sudbury (Greater Sudbury)",
        "Thunder Bay",
        "Barrie",
        "Guelph",
        "Oshawa–Durham",
        "Peterborough",
        "Brantford",
        "Belleville–Quinte West",
        "Cornwall",
        "North Bay",
        "Sault Ste. Marie",
        "Région métropolitaine de Vancouver (Vancouver + Surrey + Burnaby + Richmond + Tri‑Cities)",
        "Victoria (Capital Region)",
        "Fraser Valley (Abbotsford–Mission + Chilliwack)",
        "Kelowna",
        "Kamloops",
        "Prince George",
        "Nanaimo",
        "Courtenay–Comox",
        "Vernon",
        "Penticton",
        "Prince Rupert",
        "Terrace–Kitimat",
        "Cranbrook",
        "Williams Lake",
        "Calgary (Région métropolitaine)",
        "Edmonton (Région métropolitaine)",
        "Red Deer",
        "Lethbridge",
        "Medicine Hat",
        "Grande Prairie",
        "Fort McMurray (Wood Buffalo)",
        "Lloydminster",
        "Banff–Canmore",
        "St. Albert–Sherwood Park",
        "Saskatoon",
        "Regina",
        "Prince Albert",
        "Moose Jaw",
        "North Battleford",
        "Yorkton",
        "Swift Current",
        "Winnipeg (Région métropolitaine)",
        "Brandon",
        "Steinbach",
        "Thompson",
        "Portage la Prairie",
        "Selkirk",
        "Moncton–Dieppe–Riverview (Grand Moncton)",
        "Saint John",
        "Fredericton",
        "Bathurst",
        "Edmundston",
        "Miramichi",
        "Campbellton",
        "Halifax (Région métropolitaine)",
        "Sydney (Cape Breton)",
        "Truro",
        "New Glasgow",
        "Kentville–Wolfville",
        "Yarmouth",
        "Bridgewater",
        "Charlottetown",
        "Summerside",
        "St. John’s (Région métropolitaine)",
        "Corner Brook",
        "Gander",
        "Grand Falls–Windsor",
        "Happy Valley–Goose Bay",
        "Labrador City–Wabush",
        "Whitehorse",
        "Dawson City",
        "Yellowknife",
        "Hay River",
        "Inuvik",
        "Iqaluit",
        "Rankin Inlet (Kangiqliniq)",
        "Cambridge Bay (Iqaluktuuttiaq)",
        "Amsterdam",
        "Rotterdam",
        "La Haye",
        "Utrecht",
        "Eindhoven",
        "Tilburg",
        "Groningue",
        "Almere",
        "Bréda",
        "Nimègue",
        "Amsterdam–Rotterdam–La Haye–Utrecht (RMR)",
        "Amsterdam",
        "Haarlem",
        "Alkmaar",
        "Zaanstad (Zaandam)",
        "Haarlemmermeer (Hoofddorp–Schiphol)",
        "Hilversum",
        "Purmerend",
        "Den Helder",
        "Hoorn",
        "Rotterdam",
        "Den Haag (La Haye)",
        "Leiden",
        "Delft",
        "Dordrecht",
        "Gouda",
        "Zoetermeer",
        "Schiedam",
        "Vlaardingen",
        "Spijkenisse (Nissewaard)",
        "Alphen aan den Rijn",
        "Leerdam–Gorinchem",
        "Utrecht",
        "Amersfoort",
        "Nieuwegein",
        "Houten",
        "Veenendaal",
        "Zeist",
        "Almere",
        "Lelystad",
        "Dronten",
        "Zeewolde",
        "Arnhem",
        "Nijmegen",
        "Apeldoorn",
        "Ede–Wageningen",
        "Doetinchem",
        "Zutphen",
        "Tiel",
        "Harderwijk",
        "Zwolle",
        "Enschede",
        "Deventer",
        "Almelo",
        "Hengelo",
        "Kampen",
        "Hardenberg",
        "Assen",
        "Emmen",
        "Hoogeveen",
        "Meppel",
        "Groningen",
        "Delfzijl–Eemshaven",
        "Veendam",
        "Leeuwarden",
        "Drachten (Smallingerland)",
        "Heerenveen",
        "Sneek (Súdwest-Fryslân)",
        "Harlingen",
        "Eindhoven",
        "Tilburg",
        "Breda",
        "’s-Hertogenbosch (Den Bosch)",
        "Helmond",
        "Roosendaal",
        "Bergen op Zoom",
        "Oss",
        "Meierijstad (Veghel–Uden–Schijndel)",
        "Waalwijk",
        "Moerdijk (Zone portuaire)",
        "Maastricht",
        "Heerlen–Kerkrade (Parkstad)",
        "Sittard–Geleen (Chemelot)",
        "Roermond",
        "Venlo",
        "Weert",
        "Middelburg",
        "Vlissingen",
        "Terneuzen",
        "Goes",
        "Tilburg–Waalwijk–Moerdijk–Breda (chaîne)",
        "Zwolle–Deventer–Apeldoorn (chaîne)",
        "Helsing酶r",
        "N忙stved",
        "Slagelse",
        "Holb忙k",
        "Kalundborg",
        "Ringsted",
        "Nyk酶bing Falster",
        "Vordingborg",
        "R酶nne (Bornholm)",
        "Nakskov",
        "Maribo",
        "Haslev",
        "Sor酶",
        "Sk忙lsk酶r",
        "Greve",
        "Hiller酶d",
        "Hundige",
        "H酶je-Taastrup",
        "Roskilde",
        "K酶ge",
        "Helsing酶r",
        "Birker酶d",
        "Aller酶d",
        "Frederikssund",
        "Nyk酶bing Sj忙lland",
        "Odense",
        "Svendborg",
        "Nyborg",
        "Middelfart",
        "Assens",
        "Faaborg",
        "Bogense",
        "Ringe",
        "Kolding",
        "Vejle",
        "Haderslev",
        "Aabenraa",
        "S酶nderborg",
        "T酶nder",
        "Vejen",
        "Grindsted",
        "Give",
        "Billund",
        "Aarhus",
        "Silkeborg",
        "Randers",
        "Horsens",
        "Herning",
        "Viborg",
        "Skanderborg",
        "Ikast",
        "Holstebro",
        "Lemvig",
        "Struer",
        "Ringk酶bing",
        "Brande",
        "Thyregod",
        "Ebeltoft",
        "Grenaa",
        "Bjerringbro",
        "Skive",
        "Aalborg",
        "Hj酶rring",
        "Frederikshavn",
        "Br酶nderslev",
        "N酶rresundby",
        "St酶vring",
        "S忙by",
        "Thisted",
        "Skagen",
        "Hirtshals",
        "Pandrup",
        "L酶kken",
        "Aars",
        "L酶gst酶r",
        "Fjerritslev",
        "Brovst",
        "Sindal",
        "Tranebjerg (Sams酶)",
        "T贸rshavn (脦les F茅ro茅)",
        "Nuuk (Groenland)",
      ],
      required: true,
    },
    {
      name: "officeAddress",
      label: "Adresse du bureau",
      type: "text",
      pattern: "^[a-zA-ZÀ-ÿ0-9 ,.'-]+$",
      minlength: 50,
      maxlength: 200,
      required: true,
    },
    {
      name: "branches",
      label: "Ajouter des succursales",
      type: "branches",
      required: true,
    },
  ],
};
