export const countries = [
  "France",
  "Allemagne",
  "Norvège",
  "Suède",
  "Canada",
  "Pays-Bas",
  "Danemark",
  "Royaume-Uni",
  "Émirats Arabes Unis (UAE)",
];

export const cities = [
  "Paris",
  "Marseille",
  "Lyon",
  "Toulouse",
  "Nice",
  "Berlin",
  "Munich",
  "Hambourg",
  "Francfort",
  "Cologne",
  "Oslo",
  "Bergen",
  "Trondheim",
  "Stavanger",
  "Drammen",
  "Stockholm",
  "Gothenburg",
  "Malmö",
  "Uppsala",
  "Västerås",
  "Toronto",
  "Vancouver",
  "Montréal",
  "Calgary",
  "Ottawa",
  "Amsterdam",
  "Rotterdam",
  "La Haye",
  "Utrecht",
  "Eindhoven",
  "Copenhague",
  "Aarhus",
  "Odense",
  "Aalborg",
  "Esbjerg",
  "Londres",
  "Manchester",
  "Birmingham",
  "Édimbourg",
  "Glasgow",
  "Dubaï",
  "Abou Dabi",
  "Charjah",
  "Ajman",
  "Fujairah",
];

export const professions = [
  "Job",
  "Educator",
  "Head of educational service",
  "Animator",
  "Integration advisor",
  "Social worker",
  "ESF Advisor",
  "ISF Technician",
  "Judicial agent",
  "Nurse",
  "Caregiver",
  "Medical-psychological help",
  "Educational support",
  "Childcare nurse",
  "Doctor",
  "Psychologist",
  "Physiotherapist",
  "Occupational therapist",
  "Speech therapist",
  "Psychomotor therapist",
  "Orthoptist",
  "Midwife",
  "Hospital worker",
  "Dietitian",
  "Medical-social transporter",
  "Other",
];

export const education = [
  "Bachelor's Degree",
  "Master's Degree",
  "PhD",
  "Professional Certification",
  "Other",
];

export const availability = ["Available", "Not Available"];
